version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: "Setup virtualenv"
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: "Run tests"
          command: "sh scripts/tests.sh"
workflows:
    "Run unit tests":
        jobs:
          - test